// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var Nodemailer = require("nodemailer");

function createTransport(host, port, auth, param) {
  return Nodemailer.createTransport({
              host: host,
              port: port,
              auth: auth
            });
}

exports.createTransport = createTransport;
/* nodemailer Not a pure module */
